image:
  # -- Name of the image repository to pull the container image from.
  repository: ghcr.io/bank-vaults/vault-operator

  # -- [Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for updating already existing images on a node.
  pullPolicy: IfNotPresent

  # -- Image tag override for the default value (chart appVersion).
  tag: "v1.21.2"

  # -- Reference to one or more secrets to be used when [pulling images](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) (from private registries).
  # (`global.imagePullSecrets` is also supported)
  imagePullSecrets:
    - name: ghcr-login-secret