---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-seeder-init-script-config
  namespace: mysql-seeder-test
data:
  create-tables.sql: |
    # Creation of the "doc_changes" table
    CREATE TABLE IF NOT EXISTS `doc_changes` (
      `tenant` varchar(255) NOT NULL,
      `id` varchar(255) NOT NULL,
      `change_id` int(10) unsigned NOT NULL,
      `user_id` varchar(255) NOT NULL,
      `user_id_original` varchar(255) NOT NULL,
      `user_name` varchar(255) NOT NULL,
      `change_data` longtext NOT NULL,
      `change_date` datetime NOT NULL,
      PRIMARY KEY (`tenant`, `id`,`change_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    # Creation of the "task_result" table
    CREATE TABLE IF NOT EXISTS `task_result` (
      `tenant` varchar(255) NOT NULL,
      `id` varchar(255) NOT NULL,
      `status` tinyint(3) NOT NULL,
      `status_info` int(10) NOT NULL,
      `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
      `last_open_date` datetime NOT NULL,
      `user_index` int(10) unsigned NOT NULL DEFAULT 1,
      `change_id` int(10) unsigned NOT NULL DEFAULT 0,
      `callback` longtext NOT NULL,
      `baseurl` text NOT NULL,
      `password` longtext NULL,
      `additional` longtext NULL,
      PRIMARY KEY (`tenant`, `id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
