---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-init-container
  namespace: mysql-seeder-test
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: mysql-seeder
      image: serverninja/alpine-db-init-runner:latest-linux-arm64
      imagePullPolicy: Always
      env:
        - name: INPUT_JSON
          value: '{ "db_scripts": [{"script_name": "create-tables.sql", "database_name": "onlyoffice_test" }]}'
        - name: DB_HOST
          value: "mysql.mysql.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
      volumeMounts:
        - name: init-script
          mountPath: /mysql-scripts
  volumes:
    - name: init-script
      configMap:
        name: mysql-seeder-init-script-config